#!/bin/ash /etc/rc.common

START=95
STOP=
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/aria2
LOG=$MPATH/log/aria2.log
CONF=$MPATH/conf/aria2.conf
BAK=$MPATH/backup
appname=aria2

start () {

	[ ! -x $BIN ] && MEO -red1t "Aria2 not installed" && exit
	uci set monlor.$appname.enable=1
	uci commit monlor
	ps | grep aria2 | grep -v grep | grep -v {aria2} > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		MEO -pur1t 'Aria2 is already running'
		exit 1
	fi
	MEO -bla1t "Starting $appname ... \c"
	#update
	[ ! -f /tmp/aria2.session ] && touch /tmp/aria2.session
	uci set monlor.$appname.version=`$BIN -v | awk '/aria2 version/{print$3}'`
	uci commit monlor
	
	iptables -I INPUT -p tcp --dport 6800 -m comment --comment "monlor-aria2" -j ACCEPT 
	service_start $BIN --conf-path=$CONF -D -l $LOG
	if [ $? -eq 0 ]; then
                MEO -gre1 "Done!"
        else
                MEO -red1 'Failed!'
        fi

}

stop () {

	[ ! -x $BIN ] && MEO -red1t "Aria2 not installed" && exit
	uci set monlor.$appname.enable=0
	uci commit monlor
	MEO -bla1t "Stopping $appname ... \c"
	service_stop $BIN
	ps | grep $BIN | grep -v grep | awk '{print$1}' | xargs kill -9 > /dev/null 2>&1
	iptables -D INPUT -p tcp --dport 6800 -m comment --comment "monlor-aria2" -j ACCEPT > /dev/null 2>&1
	MEO -gre1 "Done!"

}

restart () {

	stop
	sleep 2
	start

}

enable() {

	$MPATH/script/update $appname

}

disable() {

	uci set monlor.$appname.enable=0
	uci commit monlor
	stop
	MEO -bla1t "Delete $appname files ... \c"
	rm -rf $BIN $CONF $LOG 
	MEO -gre1 "Done!"

}
