#!/bin/ash /etc/rc.common

START=95
STOP=
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/fastdick
LOG=$MPATH/log/fastdick.log
CONF=$MPATH/conf/fastdick.conf
BAK=$MPATH/backup
appname=fastdick

getconfig () {

	[ ! -f $CONF ] && MEO -red1 "No config" && touch $CONF && exit
	uid=`cat $CONF | awk -F ':' '/uid/{print$2}'`
	pwd=`cat $CONF | awk -F ':' '/pwd/{print$2}'`
	peerid=`cat $CONF | awk -F ':' '/peerid/{print$2}'`
	sed -i '14s/.*/uid=$uid/' $BIN
	sed -i '15s/.*/pwd=$pwd/' $BIN
	sed -i '17s/.*/peerid=$peerid/' $BIN

}

start () {

	[ ! -x $BIN ] && MEO -red1t "Fastdick not installed" && exit
	uci set monlor.$appname.enable=1
	uci commit monlor
	ps | grep fastdick | grep -v grep > /dev/null 2>&1
	if [ $? -eq 0 ]; then                                                              
		MEO -pur1t 'Fastdick is already running'                                            
		exit 1
	fi
	MEO -bla1t "Starting $appname .... \c"
	getconfig   
	uci set monlor.$appname.version=2.0.3.4
	uci commit monlor
	echo `date` > $LOG	
	
	#/bin/sh $BIN & 
	service_start $BIN
	if [ $? -eq 0 ]; then
                MEO -gre1 "Done!"
        else
                MEO -red1 'Failed!'
        fi

}

stop () {

	[ ! -x $BIN ] && MEO -red1t "Fastdick not installed" && exit
	uci set monlor.$appname.enable=0
	uci commit monlor
	MEO -bla1t "Stopping $appname .... \c"
	kill -9 $(ps | grep $BIN | grep -v grep | grep -v {fastdick} | awk '{print $1}') > /dev/null 2>&1
	MEO -gre1 "Done!"

}

restart () {

	stop
	sleep 1
	start

}

enable() {

	$MPATH/script/update $appname

}

disable() {

	uci set monlor.$appname.enable=0
	uci commit monlor
	stop
	MEO -bla1t "Delete $appname files ... \c"
	rm -rf $BIN $LOG 
	MEO -gre1 "Done!"	

}
