#!/bin/ash /etc/rc.common

START=95
STOP=
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/fastdick
LOG=$MPATH/log/fastdick.log
CONF=$MPATH/conf/fastdick.conf
BAK=$MPATH/backup

update () {

	curl -Lo /tmp/fastdick https://github.com/fffonion/Xunlei-Fastdick/raw/master/swjsq.py
	chmod +x /tmp/fastdick

}

start () {

	ps | grep fastdick | grep -v grep | grep -v {fastdick} > /dev/null 2>&1
	if [ $? -eq 0 ]; then                                                              
		MEO -pur1t 'Fastdick is already running'                                            
		exit 1
	fi
	MEO -bla1t 'Starting fastdick .... \c'
	#update
	#uci set monlor.fastdick.version=`cat $BIN | grep APP_VERSION | awk -F '"' '{print$2}'`        
	uci set monlor.fastdick.version=2.0.3.4
	uci commit monlor
	echo `date` > $LOG	
	
	#/bin/sh $BIN & 
	service_start $BIN
	if [ $? -eq 0 ]; then
                MEO -gre1 "Done!"
        else
                MEO -red1 'Failed!'
        fi

}

stop () {

	MEO -bla1t 'Stopping fastdick .... \c'
	kill -9 $(ps | grep fastdick | grep -v grep | grep -v {fastdick} | awk '{print $1}') > /dev/null 2>&1
	MEO -gre1 "Done!"

}

restart () {

	stop
	sleep 2
	start

}

enable() {

	uci set monlor.fastdick.enable=1
	uci commit monlor
	restart

}

disable() {

	uci set monlor.fastdick.enable=0
	uci commit monlor
	stop

}
