#!/bin/ash

MEO() {
	one="$1"
	two="\t$2"
	three="\t$3"
	case $1 in
		-bla*) color=";30";;
		-red*) color=";31";;
		-gre*) color=";32";;
		-yel*) color=";33";;
		-blu*) color=";34";;
		-pur*) color=";35";;
		-sbl*) color=";36";;
		-whi*) color=";37";;
		-t) color="";;
		*) 
			now=""
			color=""
			type=""
			two="$1"
			three="\t$2"
		;;
	esac
	case $1 in
		*1t) 
			now="[`date "+%Y-%m-%d %H:%M:%S" `]"
			type=";1"
			[ `echo $1 | grep 5 | wc -l` -ne 0 ] && type=";5;1"
		;;
		*5t)
			now="[`date "+%Y-%m-%d %H:%M:%S" `]"
			type=";5"
			[ `echo $1 | grep 1 | wc -l` -ne 0 ] && type=";1;5"
		;;
		*1)
			now=""
			type=";1"
			two="$2"
			three="\t$3"
			[ `echo $1 | grep 5 | wc -l` -ne 0 ] && type=";5;1"
		;;
		*5)
			now=""
			type=";5"
			two="$2"
			three="\t$3"
			[ `echo $1 | grep 1 | wc -l` -ne 0 ] && type=";1;5"
		;;
		-*t)
			now="[`date "+%Y-%m-%d %H:%M:%S" `]" 
			type=""
		;;
		*)
			type=""
			[ "$two" != "$1" ] && two="$2"
		;;
	esac
	#if [ `uci get monlor.tools.color_en` -eq 0 ]; then
	#	echo -e "$now$two$three"
	#	echo -e "$now$two$three" >> /tmp/monlor.log
	#else
		echo -e "\033[49;36;1m$now\033[0m\033[49"$color""$type"m$two\033[49"$color""$type"m$three\033[0m" 
		echo -e "\033[49;36;1m$now\033[0m\033[49$color"$type"m$two\033[49$color"$type"m$three\033[0m" >> /tmp/monlor.log
	#fi
	
}

#echo "Usage: MEO -(color+type+time) anything"
