#!/bin/ash /etc/rc.common

START=95
STOP=
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/nginx
LOG=$MPATH/log/nginx.log
CONF=$MPATH/conf/nginx.conf

get_config() {

	rm -rf $CONF
	echo -e "error_log  "$LOG"  info;" >> $CONF
	echo -e "events {\n\tworker_connections  1024;\n}" >> $CONF
	echo -e "http {\n\tinclude       mime.types;" >> $CONF
	echo -e "\tdefault_type  application/octet-stream;" >> $CONF
	echo -e "\tsendfile        on;" >> $CONF
	echo -e "\tkeepalive_timeout  65;" >> $CONF
	echo -e "\tclient_max_body_size 4G;" >> $CONF
	
	cat $MPATH/conf/nginxlist | while read line
	do
		[[ ${line:0:1} == "#" ]] && continue
		echo -e "\n\tserver{" >> $CONF
		echo -e "\tserver_name `echo $line | awk -F ',' '{print$1}'`;" >> $CONF
		server_port=`echo $line | awk -F ',' '{print$2}'`
		echo -e "\tlisten $server_port;" >> $CONF
		iptables -I INPUT -p tcp --dport $server_port -j ACCEPT -m comment --comment "monlor-nginx"
		echo -e "\t`echo $line | awk -F ',' '{print$4}'`" >> $CONF
		echo -e "\tlocation / {" >> $CONF
		echo -e "\t\troot `echo $line | awk -F ',' '{print$3}'`;" >> $CONF
		echo -e "\t\tindex  index.html index.htm;" >> $CONF
		echo -e "\t\t\tautoindex on;" >> $CONF
		echo -e "\t\t\tautoindex_exact_size on;" >> $CONF
		echo -e "\t\t\tautoindex_localtime on;" >> $CONF
		echo -e "\t\t}\n\t}" >> $CONF
	done
	
	echo "}" >> $CONF

}

start () {

	result=`ps | grep -E 'worker process|master process' | grep -v grep | grep -v sysapihttpd | wc -l`
	if [ $result -ne 0 ]; then
		MEO -pur1t 'Nginx is already running'
		exit 1
	fi
	uci set monlor.nginx.version=1.6.0
	uci commit monlor
	echo `date` > $LOG
	MEO -bla1t 'Starting nginx ... \c' 
	get_config
	service_start $BIN -c $CONF -p $MPATH/bin
	if [ $? -eq 0 ]; then
                MEO -gre1 'Done!'
        else
                MEO -red1 'Failed!'
        fi


}

stop () {

	MEO -bla1t 'Stopping nginx ... \c'
	service_stop $BIN
	#kill -9 $(ps | grep nginx | grep -v grep | grep -v sysapihttpd | awk '{print $1}')
	ps | grep -E 'worker process|master process' | grep -v grep | grep -v sysapihttpd | awk '{print$1}' | xargs kill -9 > /dev/null 2>&1
	iptables -S | grep nginx | sed 's/-A/iptables -D/g' > /tmp/clean.sh && chmod +x /tmp/clean.sh && /tmp/clean.sh && rm -rf clean.sh > /dev/null 2>&1
	MEO -gre1 'Done!'

}

restart () {

	stop
	sleep 2
	start

}

enable() {

	uci set monlor.nginx.enable=1
	uci commit monlor
	restart

}

disable() {

	uci set monlor.nginx.enable=0
	uci commit monlor
	stop

}
