#!/bin/ash
MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho
MEO "*****************************************"
MEO -blu1 "Testing ss server ... "
MEO "*****************************************"
MEO -sbl1 "ss_name\tss_server\ttime/loss"
MEO "*****************************************"
cat /tmp/ping_tmp | while read line
do
	ss_name=`uci show monlor | grep -B 5 $line | grep ss_name | awk -F '=' '{print$2}'`
        MEO "$ss_name\t$line\t\c"
	ping_text=`ping -4 $line -c 4 -w 10 -q` > /dev/null 2>&1
	ping_time=`echo $ping_text | grep avg | awk -F '/' '{print$5}' | awk '{print$1}'`
	ping_loss=`echo $ping_text | grep loss | awk -F ',' '{print$3}' | awk '{print$1}'`
	if [ ! -z $(echo $ping_time | sed 's/[^.]//g') ]; then 
		MEO -gre ""$ping_time"ms/$ping_loss\t" 
	        uci set monlor.$ss_name.ss_ping="$ping_time"       
	else
		MEO -red "bad"
		uci set monlor.$ss_name.ss_ping="bad"
	fi
done
uci commit monlor
MEO "*****************************************"                                         
MEO -blu1 "Testing ss success!"
MEO "*****************************************" 
