#!/bin/ash

ssname=$2
MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

add() {
	 [ ! -z /etc/config/monlor ] && touch /etc/config/monlor > /dev/null 2>&1
	 #config setting and save settings.
	 MEO -bla "************************************"
	 MEO -blu1 "Please input your ss config"
	 MEO -blu1 " (ctrl + c to exit)"
	 MEO -bla "************************************"
	 MEO  "Input ss name:\c"
	 read ssname
	 [ -f $ssname ] && MEO -red1 "Please input ss name, exit ... " && exit
	 MEO "Input server ip:\c"
	 read serverip
	 [ -f $serverip ] && serverip=`uci get monlor.$ssname.ss_server` && MEO -gre1 $serverip
	 MEO "Input server port:\c"
	 read serverport
	 [ -f $serverport ] && serverport=`uci get monlor.$ssname.ss_server_port` && MEO -gre1 $serverport
	 MEO "Input server passwd:\c"
	 read shadowsockspwd
	 [ -f $shadowsockspwd ] && shadowsockspwd=`uci get monlor.$ssname.ss_password` && MEO -gre1 $shadowsockspwd
	 MEO "(1:aes-256-cfb 2:rc4-md5 3:chacha20 or input other method)\nInput server method:\c"
	 read method
	 [ -f $method ] && method=`uci get monlor.$ssname.ss_method` && MEO -gre1 $method
 	 MEO "(1:gfwlist 2:whitelist 3:wholemode 4: empty)\nInput ss mode:\c"
 	 read ssmode
 	 [ -f $ssmode ] && ssmode=`uci get monlor.$ssname.ss_mode` && MEO -gre1 $ssmode
 	 MEO "(1:cngame 2:frgame 3:empty)\nInput ssg mode:\c"         
	 read ssgmode
	 [ -f $ssgmode ] && ssgmode=`uci get monlor.$ssname.ssg_mode` && MEO -gre1 $ssgmode

	 case $method in
	 	1|aes-256-cfb) method=aes-256-cfb;;
		2|rc4-md5) method=rc4-md5;;
		3|chacha20) method=chacha20;;
	 esac
	 case $ssmode in
	 	1|gfwlist) ssmode=gfwlist;;
		2|whitelist) ssmode=whitelist;;
		3|wholemode) ssmode=wholemode;;
		4|"") ssmode=empty;;
	 esac
	 case $ssgmode in
	 	1|cngame) ssgmode=cngame;;
	 	2|frgame) ssgmode=frgame;;
	 	3|"") ssgmode=empty;;
	 esac
 	 
	 # Config shadowsocks
	 uci set monlor.$ssname=ss
	 uci set monlor.$ssname.ss_name=$ssname
	 uci set monlor.$ssname.ss_server=$serverip
	 uci set monlor.$ssname.ss_server_port=$serverport
	 uci set monlor.$ssname.ss_password=$shadowsockspwd
	 uci set monlor.$ssname.ss_method=$method
	 uci set monlor.$ssname.ss_mode=$ssmode
	 uci set monlor.$ssname.ssg_mode=$ssgmode
	 uci commit monlor
	 echo "$serverip" > /tmp/ping_tmp
	 $MPATH/script/ss_ping
	 rm -rf /tmp/ping_tmp
	 MEO "************************************"
	 $MPATH/script/ssconf show | grep -w -A 7 $ssname
	 MEO "************************************"
	 MEO -blu1 "Add ss config sucess!" 
	 MEO "************************************"
}
 
show() {
 	
 	MEO "************************************"	
	MEO -blu1 'Your ss server list is'
	#uci show monlor.ss.ss_name | cut -b 19-20
 	#uci show monlor | cut -b 8-9 | sed '$!N;/^\(.*\)\n\1$/!P;D' | sed -e "s/ss//g"
 	#uci show monlor | awk -F "=" '/ss_name/{print$2}'
 	#echo -e "ss_name \tss_server \tss_mode \tssg_mode"
 	#uci show monlor | awk -F "=" '/ss_name/{printf$2"\t"};/ss_server=/{printf$2"\t"};/ss_mode/{printf$2"\t"};/ssg_mode/{print$2}'
 	MEO "************************************"
 	if [ -f $ssname ]; then
 		uci export monlor | grep -A 7 ss_name | awk '{if ($1!="--") print $2" "$3; else print "************************************"}'
	elif [ "$ssname" == "ping" ]; then
                echo
                uci export monlor | grep -E 'ss_name|ss_ping' | awk '{if($2=="ss_ping")print$3"\n"; else printf$2" "$3" "}'
 	else
  		uci export monlor | grep -A 7 "ss_name '$ssname'" | awk '{print $2" "$3}'
 	fi
 	MEO "************************************"
 	MEO -blu1 "Input (ssconf del server) to delete"
 	MEO "************************************"
 	
}
 
del() {
 
 	if [ -f $ssname ]; then
 		MEO -blu1 'Input nothing, exit ... '
 		exit
 	fi
	uci show monlor | grep -w ss_name=$ssname > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		MEO -blu1 'no this server, exit ... '
		exit
	fi
 	MEO -blu1 "Sure to del $ssname(`uci get monlor.$ssname.ss_server`:`uci get monlor.$ssname.ss_server_port`)(y/n)? \c"
 	read ans
 	if [ $ans == "y" ]; then
 		uci del monlor.$ssname > /dev/null 2>&1
 		uci commit monlor
 		ssname=""
		show
	else	
		MEO "\c"
		exit
	fi 	
 
}

ping() {

	uci show monlor | grep -w ss_server | awk -F '=' '{print$2}' > /tmp/ping_tmp
	"$MPATH"/script/ss_ping
	rm -rf /tmp/ping_tmp

}

backup () {

	uci show monlor | grep "monlor.*.ss" | grep -v "monlor.ss" | sed -e 's/^/uci set /g' > /tmp/ss_backup
	MEO -bla1t "Backup success -> /tmp/ss_backup"

}

recover () {

	if [ -f /tmp/ss_backup ]; then
		chmod +x /tmp/ss_backup
		touch /etc/config/monlor > /dev/null 2>&1
		/tmp/ss_backup
		uci commit monlor
		MEO -bla1t "Recover success ... "
	else
		MEO -bla1t "/tmp/ss_backup not found"
	fi

}
 
case $1 in
 	add) add;;
 	show) show;;
 	del) del;;
 	ping) ping;;
 	backup) backup;;
 	recover) recover;;
 	*) MEO "Usage: $0 {add|show|del|ping|backup|recover}"
esac
