#!/bin/ash /etc/rc.common

START=95
STOP=
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/tinyproxy
LOG=$MPATH/log/tinyproxy.log
CONF=$MPATH/conf/tinyproxy.conf

start () {

	ps | grep tinyproxy | grep -v grep | grep -v {tinyproxy} > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		MEO -pur1t 'Tinyproxy is already running'
		exit 1
	fi
	uci set monlor.tinyproxy.version=`$BIN -v | awk '{print$2}'`	
	uci commit monlor
	echo `date` > $LOG	
	MEO -bla1t 'Starting tinyproxy ... \c' 
	
	iptables -I INPUT -p tcp --dport 8888 -m comment --comment "monlor-tinyproxy" -j ACCEPT
	service_start $BIN -c $CONF 
	if [ $? -eq 0 ]; then
                MEO -gre1 'Done!'
        else
                MEO -red1 'Failed!'
        fi


}

stop () {

	MEO -bla1t 'Stopping tinyproxy ... \c'
	service_stop $BIN
	iptables -D INPUT -p tcp --dport 8888 -m comment --comment "monlor-tinyproxy" -j ACCEPT > /dev/null 2>&1
	MEO -gre1 'Done!'

}

restart () {

	stop
	sleep 2
	start

}

enable() {

	uci set monlor.tinyproxy.enable=1
	uci commit monlor
	restart

}

disable() {

	uci set monlor.tinyproxy.enable=0
	uci commit monlor
	stop

}
