#!/bin/ash /etc/rc.common

MPATH=`uci get monlor.tools.mpath`
. $MPATH/script/mecho

BIN=$MPATH/bin/vsftpd
LOG=$MPATH/log/vsftpd.log
CONF=$MPATH/conf/vsftpd.conf
BAK=$MPATH/backup

get_config() {

	MEO -bla1t "Load vsftpd setting ... \c"
	
	[ `uci show monlor.vsftpd | grep root_enable | wc -l` -eq 0 ] && uci set monlor.vsftpd.root_enable=1
	[ `uci show monlor.vsftpd | grep anon_enable | wc -l` -eq 0 ] && uci set monlor.vsftpd.anon_enable=1
	[ `uci show monlor.vsftpd | grep write_enable | wc -l` -eq 0 ] && uci set monlor.vsftpd.write_enable=1
	[ `uci show monlor.vsftpd | grep chroot | wc -l` -eq 0 ] && uci set monlor.vsftpd.chroot=1
	[ `uci show monlor.vsftpd | grep log_enable | wc -l` -eq 0 ] && uci set monlor.vsftpd.log_enable=0
	[ `uci show monlor.vsftpd | grep ftp_port | wc -l` -eq 0 ] && uci set monlor.vsftpd.ftp_port=" "
	
	[ `uci get monlor.vsftpd.root_enable` = "1" ] && echo "root" >> /etc/vsftpd.users || touch /etc/vsftpd.users 
	cat $MPATH/conf/ftpuser.conf >> /etc/vsftpd.users
	if [ `uci get monlor.vsftpd.anon_enable` = "1" ]; then 
		anon_enable=YES 
		mkdir -p /var/ftp/pub > /dev/null 2>&1
		sed -i '/ftp/d' /etc/passwd
		sed -i '/ftp/d' /etc/shadow
		echo "ftp:*:10086:10086:ftp:/var/ftp:/bin/false" >> /etc/passwd
		echo "ftp:*:0:0:99999:7:::" >> /etc/shadow
		echo -e "123456\n123456" | passwd ftp > /dev/null 2>&1
	else
		anon_enable=NO 
	fi
	[ `uci get monlor.vsftpd.write_enable` = "1" ] && write_enable=YES || write_enable=NO
	[ `uci get monlor.vsftpd.chroot` = "1" ] && chroot=YES || chroot=NO
	[ `uci get monlor.vsftpd.log_enable` = "1" ] && xferlog_enable=YES || xferlog_enable=NO
	[ -f `uci get monlor.vsftpd.ftp_port` ] && ftp_port=21
	cp -rf $CONF /etc/vsftpd.conf
	echo -e '\nanonymous_enable='$anon_enable'\nchroot_local_user='$chroot'\nlisten_port='$ftp_port'\nwrite_enable='$write_enable'\nxferlog_enable='$xferlog_enable'\n' >> /etc/vsftpd.conf
	MEO -gre1 "Done!"	

}

start () {

	ps | grep vsftpd | grep -v grep | grep -v {vsftpd} > /dev/null 2>&1
	if [ $? -eq 0 ]; then                                                              
		MEO -pur1t 'Vsftpd is already running'                                            
		exit 1
	fi
	get_config
	MEO -bla1t 'Starting vsftpd .... \c'
	#update
	#uci set monlor.vsftpd.version=`$BIN -v | awk '{print$3}'`        
	uci set monlor.vsftpd.version=3.0.3
	uci commit monlor
	echo `date` > $LOG	
	mkdir -m 0755 -p /var/ftp/pub	
	
	iptables -I INPUT -p tcp --dport 21 -j ACCEPT -m comment --comment "monlor-vsftpd"
	service_start $BIN > /dev/null 2>&1
	if [ $? -eq 0 ]; then
                MEO -gre1 "Done!"
        else
                MEO -red1 'Failed!'
        fi

}

stop () {

	MEO -bla1t 'Stopping vsftpd .... \c'
	service_stop $BIN
	kill -9 $(ps | grep vsftpd | grep -v grep | grep -v {vsftpd} | awk '{print $1}') > /dev/null 2>&1
	rm -rf /etc/vsftpd*
	iptables -D INPUT -p tcp --dport 21 -j ACCEPT -m comment --comment "monlor-vsftpd" > /dev/null 2>&1
	MEO -gre1 "Done!"

}

restart () {

	stop
	sleep 2
	start

}

enable() {

	uci set monlor.vsftpd.enable=1
	uci commit monlor
	restart

}

disable() {

	uci set monlor.vsftpd.enable=0
	uci commit monlor
	stop

}

